# This is a TOML file representing an instance of the concept of `Molecule` in MAMBO
# In particular, we are instantiating a DPBIC molecule, in its "initial" conditions and that we'll use to create a bulk of DPBIC moleculs

title = "DPBIC_single_molecule"

description = """
If one need to write a long and verbose description \
or if it could be useful to report an extract of the original article...
It can be done here!
"""

[owner] # This is the only section that is not in MAMBO. It's not "intrinsic" to molecular materials(?)
name = "Matteo Baldoni"
country = "Italy"
institute = "CNR-ISMN"

[material]
name = "DPBIC"
entity_type = "Molecular system"
formula = "C57H42IrN6"
material.structure.xyz = "DPBIC_single_molecule.xyz"
material.structure.pdb = "DPBIC_single_molecule.pdb"
material.property.pre = [ "DPBIC_single_molecule.pdb" ]
material.property.measured = [ "DPBIC_single_molecule_measured.csv" ]
material.property.computed = [ "DPBIC_single_molecule_computed.csv" ]

[provenance]
computed_by = "" # Name of the TOML file corresponding to the computation that led to this result/file (empty here since it is not computed(?))
measured_by = "" # Same as above, but for measurements

